// CERTIFICATES
export const certificates = [
	{
		name: "The Complete Web Developer 2020",
		description: "",
		url: "/cert_completeweb.jpg",
		icon: "/react.svg",
		duration: 35,
	},
	{
		name: "Java Programming Masterclass for Software Developers",
		description: "",
		url: "/cert_java.jpg",
		icon: "/java.svg",
		duration: 80.5,
	},
	{
		name: "Angular - The Complete Guide",
		description: "",
		url: "/cert_angular.jpg",
		icon: "/angular.svg",
		duration: 33.5,
	},
	{
		name: "Modern HTML & CSS from the beginning",
		description: "",
		url: "/cert_html.jpg",
		icon: "/html.svg",
		duration: 21,
	},
	{
		name: "Modern Javascript from the beginning",
		description: "",
		url: "/cert_javascript.jpg",
		icon: "/javascript.svg",
		duration: 21.5,
	},
	{
		name: "Node.js API Masterclass with Express and MongoDB",
		description: "",
		url: "/cert_node.jpg",
		icon: "/node.svg",
		duration: 12,
	},
	{
		name: "React front to back",
		description: "",
		url: "/cert_react.jpg",
		icon: "/react.svg",
		duration: 14,
	},
	{
		name: "Microfrontends with React: A complete developer's guide",
		description: "",
		url: "/cert_microreact.jpg",
		icon: "/react.svg",
		duration: 9,
	},
	{
		name: "Nodejs: Advanced Concepts",
		description: "",
		url: "/cert_advancednode.jpg",
		icon: "/node.svg",
		duration: 16,
	},
];
